#!/usr/bin/env python3
"""Build a WeChat article Markdown wrapper for a generated podcast."""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from urllib.parse import urlparse


def clean(value: str) -> str:
    return re.sub(r"\s+", " ", value.strip())


def read_info(path: Path) -> tuple[str, str]:
    text = path.read_text(encoding="utf-8-sig")
    title_match = re.search(r"标题[:：]\s*(.*?)(?:\n\s*\n|\r?\n简介[:：])", text, re.S)
    desc_match = re.search(r"简介[:：]\s*(.*)", text, re.S)
    title = clean(title_match.group(1)) if title_match else ""
    description = clean(desc_match.group(1)) if desc_match else ""
    if not title or not description:
        raise SystemExit(f"Cannot parse title and description from {path}")
    return title, description


def is_http_url(value: str) -> bool:
    parsed = urlparse(value.strip())
    return parsed.scheme in {"http", "https"} and bool(parsed.netloc)


def clip(value: str, limit: int) -> str:
    value = clean(value)
    return value[:limit]


def main() -> int:
    parser = argparse.ArgumentParser(description="Build podcast Markdown for WeChat draft upload.")
    parser.add_argument("--audio", required=True, help="Generated audio file path.")
    parser.add_argument("--info", help="TXT generated by make_podcast_info.py.")
    parser.add_argument("--cover", help="Generated cover JPG path.")
    parser.add_argument("--output", required=True, help="Output Markdown path.")
    parser.add_argument("--title", help="Podcast title override.")
    parser.add_argument("--description", help="Podcast description override.")
    parser.add_argument("--author", default="Codex", help="WeChat article author.")
    parser.add_argument("--source-title", default="", help="Original source title.")
    parser.add_argument("--source-url", default="", help="Original source URL, if any.")
    parser.add_argument("--audio-url", default="", help="Public audio URL, if available.")
    args = parser.parse_args()

    audio = Path(args.audio)
    if not audio.exists():
        raise SystemExit(f"Audio file does not exist: {audio}")

    cover = Path(args.cover) if args.cover else None
    if cover and not cover.exists():
        raise SystemExit(f"Cover file does not exist: {cover}")

    info_title = info_description = ""
    if args.info:
        info_title, info_description = read_info(Path(args.info))

    title = clip(args.title or info_title or audio.stem, 32)
    description = clip(args.description or info_description, 220)
    if not description:
        raise SystemExit("Description is required via --description or --info")

    digest = clip(description, 128)
    source_url = args.source_url.strip() if is_http_url(args.source_url) else ""
    audio_url = args.audio_url.strip() if is_http_url(args.audio_url) else ""

    lines = [
        "---",
        f'title: "{title}"',
        f'author: "{clip(args.author, 16)}"',
        f'digest: "{digest}"',
        f'source: "{source_url}"',
        "---",
        "",
    ]

    if cover:
        lines.extend([f"![{title}]({cover.as_posix()})", ""])

    lines.extend(
        [
            f"# {title}",
            "",
            description,
            "",
            "## 本期音频",
            "",
        ]
    )

    if audio_url:
        lines.extend([f"- 在线音频：[{audio_url}]({audio_url})"])
    lines.extend(
        [
            f"- 本地音频文件：`{audio}`",
            "- 发布前请确认公众号后台是否支持直接插入该音频素材；如果当前 md2wechat 能力不支持音频嵌入，不要伪造外链。",
            "",
        ]
    )

    if args.source_title or source_url:
        lines.extend(["## 来源", ""])
        if args.source_title:
            lines.append(f"- 原始标题：{args.source_title}")
        if source_url:
            lines.append(f"- 原文链接：{source_url}")
        lines.append("")

    lines.extend(
        [
            "## 简介",
            "",
            description,
            "",
        ]
    )

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
